### ISSUE TITLE
Legend positioning

### ISSUE THREAD

**Issue by mattlee821** [NightingaleHealth/ggforestplot#2]
Hey! I'm having issues with the legend not fitting on the plot (attached screenshot). I've tried to look through the functions to figure out where you specify the exact positioning of the legend but can't figure it out to edit this myself- maybe it is defined by `patchwork::wrap_plots`....

This only seems to be an issue when wrapping multiple forestplots together (following [this guide](https://nightingalehealth.github.io/ggforestplot/articles/ggforestplot.html#grouping-the-biomarkers)). I think this is an issue because the plot which I have as my bottom plot, the one in which the legend is positioned relative to, is smaller in height than the legend it self. In the attached screenshot i know there is a 'model1' label missing below the 'model2' label but this has been pushed off the plot.

If i increase the height of the plot when saving (`pdf("plot.pdf", width = 8, height = 100)` the issue is resolved. But if there were a way to adjust the legend positioning outside of the overall plot size that would be useful.

![Screenshot 2020-04-06 at 16 13 18](https://user-images.githubusercontent.com/30179533/78574348-cace6800-7821-11ea-8c7a-4af0a6d6b4a0.png)

**Comment by mattlee821** [comment]
Given the new update on the vignette suggesting use of `ggforce` this can be closed as the legend is now central in plots.

**Comment by mariakalimeri** [comment]
Hey! Very sorry for not noticing this earlier (must have missed the email with the original opening of this issue). But good that this is now, indirectly, fixed!
